---
title: "Exploring Categorical Data"
output: learnr::tutorial
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(learnr)
library(descriptr)
library(dplyr)
library(forcats)
library(magrittr)
library(gmodels)
library(readr)
library(ggplot2)
ecom <- readr::read_csv('https://raw.githubusercontent.com/rsquaredacademy/datasets/master/web.csv', 
  col_types = list(col_integer(), 
  col_factor(levels = c('bing', 'direct', 'google', 'social', 'yahoo')), 
  col_factor(levels = c('tablet', 'laptop', 'mobile')), 
  col_factor(levels = c('true', 'false')), 
  col_integer(), col_double(), col_double(), col_character(), 
  col_factor(levels = c('true', 'false')), col_double(), col_double())            
)
knitr::opts_chunk$set(echo = FALSE)
```

## Introduction

```{r cda20, exercise = TRUE, exercise.eval = FALSE, exercise.cap = 'One Way Tables'}
nlevels(ecom$device)
```

```{r cda21, exercise = TRUE, exercise.eval = FALSE, exercise.cap = 'One Way Tables'}
levels(ecom$device)
```

## One Way Tables

```{r cda1, exercise = TRUE, exercise.eval = FALSE, exercise.cap = 'One Way Tables'}
table(ecom$device)
```

```{r cda2, exercise = TRUE, exercise.eval = FALSE, exercise.cap = 'One Way Tables'}
freq_table(ecom$device)
```

```{r cda3, exercise = TRUE, exercise.eval = FALSE, exercise.cap = 'One Way Tables'}
ecom %>%
  count(device)
```

```{r cda4, exercise = TRUE, exercise.eval = FALSE, exercise.cap = 'One Way Tables'}
ecom %>%
  group_by(device) %>%
  tally()
```

```{r cda5, exercise = TRUE, exercise.eval = FALSE, exercise.cap = 'One Way Tables'}
ecom %>%
  use_series(referrer) %>%
  fct_count()
```

## Multiple One Way Tables

```{r cda6, exercise = TRUE, exercise.eval = FALSE, exercise.cap = 'Multiple One Way Tables'}
oway_tables(ecom)
```

## Two Way Tables

```{r cda7, exercise = TRUE, exercise.eval = FALSE, exercise.cap = 'Two Way Tables'}
table(ecom$device, ecom$referrer)
```

```{r cda8, exercise = TRUE, exercise.eval = FALSE, exercise.cap = 'Two Way Tables'}
mytab <- table(ecom$device, ecom$referrer)
prop.table(mytab)
prop.table(mytab, 1)
prop.table(mytab, 2)
```

```{r cda9, exercise = TRUE, exercise.eval = FALSE, exercise.cap = 'Two Way Tables'}
cross_table(ecom$device, ecom$referrer)
```

```{r cda10, exercise = TRUE, exercise.eval = FALSE, exercise.cap = 'Two Way Tables'}
CrossTable(ecom$device, ecom$referrer)
```

## Multiple Two Way Tables

```{r cda11, exercise = TRUE, exercise.eval = FALSE, exercise.cap = 'Multiple Two Way Tables'}
tway_tables(ecom)
```

## Three Way Tables

```{r cda12, exercise = TRUE, exercise.eval = FALSE, exercise.cap = '3 Way Tables'}
mytab <- table(ecom$device, ecom$referrer, ecom$purchase)
ftable(mytab)
```

```{r cda13, exercise = TRUE, exercise.eval = FALSE, exercise.cap = '3 Way Tables'}
mytab <- xtabs(~device+referrer+purchase, data = ecom)
ftable(mytab)
```

## Bar Chart 

```{r cda16, fig.align='center', exercise = TRUE, exercise.eval = FALSE, exercise.cap = 'Bar Chart'}
k <- cross_table(ecom$device, ecom$referrer)
plot(k)
```


## Bar Chart - Base

```{r cda14, fig.align='center', exercise = TRUE, exercise.eval = FALSE, exercise.cap = 'Bar Chart'}
mytab <- table(ecom$device, ecom$referrer)
barplot(mytab)
```

## Bar Chart - ggplot2

```{r cda15, fig.align='center', exercise = TRUE, exercise.eval = FALSE, exercise.cap = 'Bar Chart'}
ggplot(data = ecom) + 
  geom_bar(aes(device, fill = referrer))
```


## Grouped Bar Chart

```{r cda17, fig.align='center', exercise = TRUE, exercise.eval = FALSE, exercise.cap = 'Bar Chart'}
k <- cross_table(ecom$device, ecom$referrer)
plot(k, beside = TRUE)
```

## Proportional Bar Chart

```{r cda18, fig.align='center', exercise = TRUE, exercise.eval = FALSE, exercise.cap = 'Bar Chart'}
k <- cross_table(ecom$device, ecom$referrer)
plot(k, proportional = TRUE)
```

## Mosaic Plot

```{r cda19, fig.align='center', exercise = TRUE, exercise.eval = FALSE, exercise.cap = 'Bar Chart'}
k <- cross_table(ecom$device, ecom$referrer)
mosaicplot(k)
```

## Pie Chart

```{r cda22, fig.align='center', exercise = TRUE, exercise.eval = FALSE, exercise.cap = 'Pie Chart'}
# data
mytab <- ecom %>% count(referrer)
mytab

# pie chart
pie(mytab$n, labels = mytab$referrer, col = rainbow(5))
```