---
title: "Themes - Part 3"
output: learnr::tutorial
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(learnr)
library(ggplot2)
library(dplyr)
library(tidyr)
knitr::opts_chunk$set(echo = FALSE)
```


## Introduction

### Agenda

<hr>

Use `theme()` to modify the appearance of panel

- background
- border
- grid (major)
- grid (minor)

## Plot

<hr>

```{r theme9, echo=TRUE, collapse=FALSE, fig.align='center'}
p <- ggplot(mtcars) +
  geom_point(aes(disp, mpg))
p
```

## Background

### Introduction

<hr>

### Example

<hr>

```{r theme10eg, echo=TRUE, collapse=FALSE, fig.align='center'}
p + theme(panel.background = element_rect(fill = 'gray'))
```

### Instructions

<hr>

```{r theme10, fig.align='center', exercise = TRUE, exercise.eval = FALSE, exercise.cap = 'Panel Background'}
p + theme(panel.background = element_rect(fill = 'gray'))
```

```{r theme10-solution}
p + theme(panel.background = element_rect(fill = 'gray'))
```

## Border

### Introduction

<hr>

### Example

<hr>

```{r theme24eg, echo=TRUE, collapse=FALSE, fig.align='center'}
p + theme(panel.border = element_rect(fill = NA, color = 'blue', 
          linetype = 1, size = 2))
```

### Instructions

<hr>

```{r theme24, fig.align='center', exercise = TRUE, exercise.eval = FALSE, exercise.cap = 'Panel Border'}
p + theme(panel.border = element_rect(fill = NA, color = 'blue', 
          linetype = 1, size = 2))
```

```{r theme24-solution}
p + theme(panel.border = element_rect(fill = NA, color = 'blue', 
          linetype = 1, size = 2))
```

## Grid

### Introduction

<hr>

### Example

<hr>

```{r theme25eg, echo=TRUE, collapse=FALSE, fig.align='center'}
p + theme(panel.grid = element_line(color = 'blue', linetype = 2, size = 0.5))
```

### Instructions

<hr>

```{r theme25, fig.align='center', exercise = TRUE, exercise.eval = FALSE, exercise.cap = 'Panel Grid'}
p + theme(panel.grid = element_line(color = 'blue', linetype = 2, size = 0.5))
```

```{r theme25-solution}
p + theme(panel.grid = element_line(color = 'blue', linetype = 2, size = 0.5))
```

## Grid - Major

### Introduction

<hr>

### Example

<hr>

```{r theme12eg, echo=TRUE, collapse=FALSE, fig.align='center'}
p + theme(panel.grid.major.x = element_line(color = 'blue', 
          linetype = 2, size = 0.5))
```

### Instructions

<hr>

```{r theme12, fig.align='center', exercise = TRUE, exercise.eval = FALSE, exercise.cap = 'Panel Grid (Major)'}
p + theme(panel.grid.major.x = element_line(color = 'blue', 
          linetype = 2, size = 0.5))
```

```{r theme12-solution}
p + theme(panel.grid.major.x = element_line(color = 'blue', 
          linetype = 2, size = 0.5))
```

## Grid - Minor

### Introduction

<hr>

### Example

<hr>

```{r theme26eg, echo=TRUE, collapse=FALSE, fig.align='center'}
p + theme(panel.grid.minor.y = element_line(color = 'red', 
          linetype = 3, size = 0.2))
```

### Instructions

<hr>

```{r theme26, fig.align='center', exercise = TRUE, exercise.eval = FALSE, exercise.cap = 'Panel Grid (Minor)'}
p + theme(panel.grid.minor.y = element_line(color = 'red', 
          linetype = 3, size = 0.2))
```

```{r theme26-solution}
p + theme(panel.grid.minor.y = element_line(color = 'red', 
          linetype = 3, size = 0.2))
```
